// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAtakV0--FA7OGwJrfe8iuV1ohSOsPAeI',
    appId: '1:869698743095:web:ca468a1bd64a69776148b2',
    messagingSenderId: '869698743095',
    projectId: 'wallet-view',
    authDomain: 'wallet-view.firebaseapp.com',
    storageBucket: 'wallet-view.appspot.com',
    measurementId: 'G-PTLJ9XJMPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD723lkty80E_pH7XIrYSZx6Lv_9TzgcQw',
    appId: '1:869698743095:android:e5508da0f5a319be6148b2',
    messagingSenderId: '869698743095',
    projectId: 'wallet-view',
    storageBucket: 'wallet-view.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh-JihufM3ol4uabqEkW4dQZzemMlWTVQ',
    appId: '1:869698743095:ios:072d5cf32eedee2e6148b2',
    messagingSenderId: '869698743095',
    projectId: 'wallet-view',
    storageBucket: 'wallet-view.appspot.com',
    iosClientId: '869698743095-r1dp0tue91oo2hoqh6nnvck48u2ton98.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh-JihufM3ol4uabqEkW4dQZzemMlWTVQ',
    appId: '1:869698743095:ios:072d5cf32eedee2e6148b2',
    messagingSenderId: '869698743095',
    projectId: 'wallet-view',
    storageBucket: 'wallet-view.appspot.com',
    iosClientId: '869698743095-r1dp0tue91oo2hoqh6nnvck48u2ton98.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpense',
  );
}
