// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbyLHyY52qHRdiwu_TMTo-P5VnjSoxzDo',
    appId: '1:995398933121:web:d3330a9f3bd6e7fdd50b80',
    messagingSenderId: '995398933121',
    projectId: 'expense-app-c4499',
    authDomain: 'expense-app-c4499.firebaseapp.com',
    databaseURL: 'https://expense-app-c4499-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-c4499.appspot.com',
    measurementId: 'G-C9L05GTX9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkl06vNbTF1oKLTxT4jTTaSzoHIkJpvQ',
    appId: '1:995398933121:android:e0e8acfd33165577d50b80',
    messagingSenderId: '995398933121',
    projectId: 'expense-app-c4499',
    databaseURL: 'https://expense-app-c4499-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-c4499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLFv3JbWMrWilQVALgViaV70bCN9btj3k',
    appId: '1:995398933121:ios:ba0cc164bd604c5cd50b80',
    messagingSenderId: '995398933121',
    projectId: 'expense-app-c4499',
    databaseURL: 'https://expense-app-c4499-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-c4499.appspot.com',
    iosClientId: '995398933121-ev7kb41t75hjq79uji69nhvesikfrf4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLFv3JbWMrWilQVALgViaV70bCN9btj3k',
    appId: '1:995398933121:ios:ba0cc164bd604c5cd50b80',
    messagingSenderId: '995398933121',
    projectId: 'expense-app-c4499',
    databaseURL: 'https://expense-app-c4499-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-c4499.appspot.com',
    iosClientId: '995398933121-ev7kb41t75hjq79uji69nhvesikfrf4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpense',
  );
}
